// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://fymwmxxnpfnwielotuxq.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZ5bXdteHhucGZud2llbG90dXhxIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDczMzE1MjgsImV4cCI6MjA2MjkwNzUyOH0.nml0itPAxp6_ez-MSzj0MliMn2SVtpO_0f8hu-V1NGQ";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);